import { useEffect, useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import getBackendURL from '../components/GetBackendURL.jsx'
import { useInfiniteQuery, useQueryClient, useMutation } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { useSelector } from 'react-redux'
import Select from 'react-select'

const CreditHistory = () => {
  const [isLoading, setIsloading] = useState(false)

  const histories = [
    {
      id: 1,
      generatedBy: 'Adesin Paul',
      user: 'Client1',
      creditAmount: '400',
      created_at: '22-06-2025 12:00 pm'
    },
    {
      id: 2,
      generatedBy: 'Adesin Paul',
      user: 'Client1',
      creditAmount: '40',
      created_at: '22-06-2025 12:00 pm'
    },
    {
      id: 3,
      generatedBy: 'Adesin Paul',
      user: 'Client1',
      creditAmount: '100',
      created_at: '22-06-2025 12:00 pm'
    },
    {
      id: 4,
      generatedBy: 'Adesin Paul',
      user: 'Client1',
      creditAmount: '500',
      created_at: '22-06-2025 12:00 pm'
    }

  ]

  return (
    <>
      <div className="w-full mt-5 p-4 shadow-lg ">
        {isLoading ? (
          <div className="text-[#0D47A1] font-semibold text-lg">Loading...</div>
        ) : histories.length > 0 ? (
          <div className=" w-[700px] lg:w-full mx-auto relative rounded-sm lg:rounded-md">
            <table className="text-left rounded-lg  min-w-full mx-auto text-[#0D47A1]">
              <thead className="font-bold text-[25px] border-b-[0.5px] border-[#0D47A1]">
                <tr>
                  <th className="py-2 pr-4 sm:py-3">Generated By</th>
                  <th className="py-2 px-4 sm:py-3">User</th>
                  <th className="py-2 px-4 sm:py-3">Credit Amount</th>
                  <th className="py-2 px-4 sm:py-3">Date and Time</th>
                </tr>
              </thead>
              <tbody>
                {histories?.map((history, index) => (
                  <tr
                    key={history?.id}
                    className={`border-b-[0.5px] border-[#0D47A1]  font-medium text-[20px] cursor-pointer ${
                      index === histories?.length - 1 ? 'border-b-0' : ''
                    }`}
                  >
                    <td className="py-2 pr-4 sm:py-4  font-medium">{history?.generatedBy}</td>
                    <td className="py-2 px-4 sm:py-4  font-medium">{history?.user}</td>
                    <td className="py-2 px-4  sm:py-4">{history?.creditAmount}</td>

                    <td className="py-2 px-4 sm:py-4 font-medium">{history?.created_at}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="text-[#0D47A1] font-semibold text-lg">No Activities Found.</div>
        )}


         {/* {hasNextPage && (
                <div className="flex block justify-center items-center">
                  <button
                    className="rounded py-2 px-6 text-2xl bg-[#0D47A1] mb-4 mt-12 text-[#E3F2FD] cursor-pointer"
                    onClick={() => fetchNextPage()}
                    disabled={isFetchingNextPage}
                  >
                    {isFetchingNextPage ? 'Loading more...' : 'Load more'}
                  </button>
                </div>
              )} */}
      </div>
    </>
  )
}

export default CreditHistory
